### PR TITLE
Fix htmlreport python package install

### PR DESCRIPTION
**Pull request by tovrstra**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tovrstra** [comment]
@conda-forge-admin, please rerender

**Comment by tovrstra** [comment]
@seanyen @timsnyder @wolfv The PR should be ready for review. A few things had to be fixed to make all builds work. I'll YOLO-merge this on Friday, September 6 (end of this week) unless you comment earlier. Thanks!

**Comment by tovrstra** [comment]
This should also fix #81 (if it was not fixed yet). The pygments files are not present in the Windows build, see end of build log: https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/1016259/logs/150

**Review by wolfv — APPROVED** [review]

**Comment by wolfv** [comment]
Looks good to me :)

**Comment by tovrstra** [comment]
@wolfv Thanks for checking. I'll wait until Friday, just in case someone else wants to comment.

**Pull request merged**
