### PR TITLE
Provide std.cfg on macOS

### PR DESCRIPTION
**Pull request by saraedum**
On macOS, I am seeing the following error:
```
(information) Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with CFGDIR set to "/Users/travis/miniconda3/conda-bld/polygon_1548695236247/_build_env/share/Cppcheck" and will therefore search for std.cfg in that path.cppcheck: Failed to load library configuration file 'std.cfg'. Bad XML
```

For the full output, please have a look here: https://travis-ci.org/polygon-tbd/polygon/builds/485496224?utm_source=github_status&utm_medium=notification

`cppcheck --version` works fine if this file is missing, so let's add another check to see whether cppcheck can actually process files.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
I am trying to see first how I can reproduce this here.

**Comment by tovrstra** [comment]
I have no experience with OSX, so I cannot comment much. LGTM. Just let me know when this is ready to be merged.

**Comment by tovrstra** [comment]
I've been out of touch with this and merged in the hope it would work again.

**Comment by saraedum** [comment]
I don't understand why https://github.com/conda-forge/cppcheck-feedstock/pull/8#issuecomment-458226175 did not fail in the CI. Does it find the std.cfg elsewhere?

**Comment by tovrstra** [comment]
I'm also a little puzzled. I have access to a mac now for testing this, and the behavior is very strange. The package builds and tests fine within conda-bld. When I then install that package and try to use it complains about not finding the `std.cfg` file.

**Comment by tovrstra** [comment]
I assume this is some sort of failure of the relocation.

**Comment by tovrstra** [comment]
I took a closer look and it is almost certainly a relocation issue. When asking for the output in XML format, I get errors along the following lines:

```
<error id="failedToLoadCfg" severity="information" msg="Failed to load std.cfg. 
Your Cppcheck installation is broken, please re-install. The Cppcheck binary was
compiled with CFGDIR set to &quot;/Users/xxxxxxxx/miniconda3/envs/cardboardlint
-dev-python-3.7/share/Cppcheck\000\000\000\000\000\000\000\000\000\000\000\000\
000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\00
0\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\0
00\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\00
0\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\0
00\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000
\000\000\000\000&quot; and will therefore search for std.cfg in that path." ver
bose="Failed to load std.cfg. Your Cppcheck installation is broken, please re-i
nstall. The Cppcheck binary was compiled with CFGDIR set to &quot;/Users/xxxxxx
x/miniconda3/envs/cardboardlint-dev-python-3.7/share/Cppcheck\000\000\000\000\0
00\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\00
0\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\0
00\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\00
0\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\0
00\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
000\000\000\000\000\000\000\000\000\000\000\000&quot; and will therefore search
for std.cfg in that path."/>
```

When looking at the cppcheck source code, one can see that the path to the config is stored as a `std::string`, which insensitive to the null terminator, making the relocation done by the conda installer ineffective. The only solution I see for this, is to modify the cppcheck source code and to store the CFGDIR initially as a traditional C string, and then convert it to a `std::string` when needed.

**Comment by tovrstra** [comment]
Fixed in #10

**Pull request closed without merging**
